### ISSUE TITLE
Notify integration config file is outdated

### ISSUE THREAD

**Issue by wtwver** [six2dez/reconftw#374]
The latest version of Notify is using provider-config.yaml so the send zip function using old notify.conf is no longer working

# Reproduce
```
docker run -it  -v ${PWD}/provider-config.yaml:/root/.config/notify/provider-config.yaml -v ${PWD}/reconftw.cfg :/root/Tools/reconftw/reconftw.cfg six2dez/reconftw -s -d testfire.net
```

$SENDZIPNOTIFY in reconftw.cfg = true and Contents of provider-config.yaml :
```
discord:
  - id: "crawl"
    discord_channel: "crawl"
    discord_username: "test"
    discord_format: "{{data}}"
    discord_webhook_url: https://discord.com/api/webhooks/***
```

# Code affected
https://github.com/six2dez/reconftw/blob/b2402f303b8eab7ba83fd1c191b14c077ac6086b/reconftw.sh#L1736-L1759
